[package]
name = "async_monolithic"
version = "0.1.0"
edition = "2021"

[dependencies]
axstd = { git = "https://github.com/Starry-OS/axstd.git", features = ["async", "multitask", "alloc"] }
axstarry = { git = "https://github.com/Starry-OS/axstarry.git" }
