[package]
name = "async_test"
version = "0.1.0"
edition = "2021"
authors = ["Fangliang Zhao <1491657576@qq.com>"]

[dependencies]
axstd = { git = "https://github.com/Starry-OS/axstd.git", features = ["async", "multitask", "alloc", "irq"], optional = true }
